#!/usr/bin/env bash
# Regenerate flats/ + flats/MANIFEST.md from the CIP-113 blueprint — the
# non-Nix staleness guard (pattern: cardano-mpfs-onchain PR #51
# scripts/extract-blaster-uplc.sh, hardened per the identity-triple
# discipline in paolino's aiken-blaster-verification skill).
#
# `jq -er` makes a renamed or missing validator title FAIL LOUDLY instead
# of silently producing an empty flat.
#
# Modes:
#   (none)   regenerate flats/ and flats/MANIFEST.md
#   --check  RED if the committed flats or MANIFEST diverge from the
#            current blueprint/repo state (CI freshness mode). Any
#            divergence is COULD-NOT-EVALUATE for downstream claims.
#
# The MANIFEST is deterministic (no timestamps): same repo state in,
# same manifest out — so `--check` is a plain byte diff.
set -euo pipefail

# The Aiken sources, blueprint, and these flats live in the SAME repo
# (formal-verification/ is a subdirectory of cip113-programmable-tokens),
# so the source-commit axis of the identity triple is implicit: it is the
# commit containing this file.
REPO="$(cd "$(dirname "$0")/../.." && pwd)"
BLUEPRINT="$REPO/plutus.json"
FLATS="$(cd "$(dirname "$0")/.." && pwd)/flats"
MANIFEST="$FLATS/MANIFEST.md"
MODE="${1:-generate}"

declare -a TITLES=(
  "programmable_logic_base.programmable_logic_base.spend:programmable_logic_base"
  "unfracking.unfracking.withdraw:unfracking"
  "registry_mint.registry_mint.mint:registry_mint"
  "programmable_logic_global.programmable_logic_global.withdraw:programmable_logic_global"
)

if command -v shasum >/dev/null; then
  sha256() { shasum -a 256 "$1" | cut -d' ' -f1; }
  sha256_str() { printf '%s' "$1" | shasum -a 256 | cut -d' ' -f1; }
else
  sha256() { sha256sum "$1" | cut -d' ' -f1; }
  sha256_str() { printf '%s' "$1" | sha256sum | cut -d' ' -f1; }
fi

# --- Identity triple, read mechanically (never from prose) ---
COMPILER="$(jq -er '.compiler.name + " " + .compiler.version' <(jq .preamble "$BLUEPRINT"))"
PLUTUS_VERSION="$(jq -er '.preamble.plutusVersion' "$BLUEPRINT")"
BLUEPRINT_SHA="$(sha256 "$BLUEPRINT")"

emit_manifest() {
  cat <<EOF
# Flat artifact manifest — identity triple for every Lean claim

Mechanically generated by \`scripts/extract-flats.sh\`. Do not edit by
hand. \`--check\` fails RED on any divergence from the blueprint or repo
state; a claim citing flats whose manifest does not check out is
COULD-NOT-EVALUATE.

## Identity triple (commit + toolchain + semantics variant)

- **Source commit**: implicit — the Aiken sources, \`plutus.json\`, and
  these flats live in the same repository, so the source commit for every
  claim is the commit containing this manifest. CI enforces per push that
  a clean \`aiken build\` reproduces the committed blueprint and that
  these flats match it (\`--check\`).
- **Toolchain**: $COMPILER (from the blueprint's own \`.preamble.compiler\`,
  not from prose or from whatever \`aiken\` is currently installed)
- **Plutus version**: $PLUTUS_VERSION
- **BuiltinSemanticsVariant**: \`defaultFunSemanticsVariantE\` (PlutusV3,
  post-Conway). Evidence: PlutusCoreBlaster \`#prep_uplc\` builds
  \`.exec\`/\`.prop\` via \`cekExecuteProgram = cekExecuteProgramWithSemanticVariant default\`
  (\`PlutusCore/UPLC/CekMachine.lean\`), and
  \`Inhabited BuiltinSemanticsVariant := .defaultFunSemanticsVariantE\`
  (\`PlutusCore/Default/Basic.lean:54\`) — the correct variant for our
  mainnet deployment target.
- **CBOR wrapping**: \`single_cbor_hex\` — an Aiken blueprint's
  \`compiledCode\` is ONE CBOR bytestring layer around flat-encoded UPLC
  (verified empirically 2026-08-06: inner bytes start \`010100\`, the
  flat version header, not another CBOR major-type-2 byte). The
  double-wrapped form is the on-chain tx-witness encoding, not the
  blueprint encoding.

## Blueprint

- \`plutus.json\` sha256: \`$BLUEPRINT_SHA\`
- Source→blueprint reproducibility is NOT asserted by this manifest;
  it is established separately by the baseline leg of
  \`scripts/falsification-control.sh\` (clean rebuild must reproduce
  \`compiledCode\` byte-for-byte).

## Flats

| flat | blueprint title | bytes | sha256 |
|---|---|---|---|
EOF
  for entry in "${TITLES[@]}"; do
    title="${entry%%:*}"
    name="${entry##*:}"
    code="$(jq -er --arg t "$title" \
      '.validators[] | select(.title == $t) | .compiledCode' "$BLUEPRINT")"
    printf '| `%s.flat` | `%s` | %d | `%s` |\n' \
      "$name" "$title" "$((${#code} / 2))" "$(sha256_str "$code")"
  done
}

if [ "$MODE" = "--check" ]; then
  status=0
  # Leg 1: each committed flat byte-matches the current blueprint title.
  for entry in "${TITLES[@]}"; do
    title="${entry%%:*}"
    name="${entry##*:}"
    code="$(jq -er --arg t "$title" \
      '.validators[] | select(.title == $t) | .compiledCode' "$BLUEPRINT")"
    if [ "$code" != "$(cat "$FLATS/$name.flat")" ]; then
      echo "STALE: $name.flat does not match blueprint title '$title'" >&2
      status=1
    fi
  done
  # Leg 2: the committed manifest byte-matches a regeneration.
  if ! diff -u "$MANIFEST" <(emit_manifest) >&2; then
    echo "STALE: MANIFEST.md does not match current blueprint/repo state" >&2
    status=1
  fi
  [ "$status" = 0 ] && echo "flats + manifest are fresh"
  exit "$status"
fi

for entry in "${TITLES[@]}"; do
  title="${entry%%:*}"
  name="${entry##*:}"
  code="$(jq -er --arg t "$title" \
    '.validators[] | select(.title == $t) | .compiledCode' "$BLUEPRINT")"
  printf '%s' "$code" > "$FLATS/$name.flat"
  echo "wrote $name.flat ($((${#code} / 2)) bytes)"
done
emit_manifest > "$MANIFEST"
echo "wrote MANIFEST.md ($COMPILER, variant E)"
