package org.cardanofoundation.cip113.blueprint;

import com.bloxbean.cardano.client.plutus.annotation.Blueprint;

/**
 * Plutus Blueprint annotation for CIP-0113 validators.
 *
 * <p>This class uses the Cardano Client Lib's {@code @Blueprint} annotation to
 * generate Java bindings for the Aiken-compiled Plutus validators. The blueprint
 * file ({@code plutus.json}) contains all compiled validators and their metadata.
 *
 * <h2>Blueprint Generation</h2>
 * <p>The blueprint is generated by running {@code aiken build} in the on-chain
 * module. The {@code build.sh} script copies it to the Java resources directory.
 *
 * <h2>Generated Classes</h2>
 * <p>The annotation processor generates wrapper classes in the specified package
 * for each validator in the blueprint, enabling type-safe script construction.
 *
 * @see com.bloxbean.cardano.client.plutus.annotation.Blueprint
 */
@Blueprint(file = "src/main/resources/plutus.json", packageName = "org.cardanofoundation.cip113.blueprint")
public class Cip113Blueprint {
}
